server:
  port: 29100
spring:
  application:
    name: newbee-mall-cloud-gateway-admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://newbee-mall-cloud-user-service
          order: 1
          predicates:
            - Path=/users/admin/**
        - id: categories-admin-service-route
          uri: lb://newbee-mall-cloud-goods-service
          order: 1
          predicates:
            - Path=/categories/admin/**
        - id: goods-admin-service-route
          uri: lb://newbee-mall-cloud-goods-service
          order: 1
          predicates:
            - Path=/goods/admin/**
        - id: carousels-admin-service-route
          uri: lb://newbee-mall-cloud-recommend-service
          order: 1
          predicates:
            - Path=/carousels/admin/**
        - id: indexConfigs-admin-service-route
          uri: lb://newbee-mall-cloud-recommend-service
          order: 1
          predicates:
            - Path=/indexConfigs/admin/**
  redis:
    database: 13
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
